name: Deploy projects

on:
  push:
    branches:
      - 'deploy/beta'
      - 'deploy/prod'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Detect Stage        # refs/heads/deploy/beta -> beta
        run: 'echo "STAGE=${GITHUB_REF: -4}" >> $GITHUB_ENV'

      - name: Setup repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Check that deploy branch is behind main
      #   run: git merge-base --is-ancestor HEAD refs/remotes/origin/main

      - name: Install dependencies
        run: npm ci --also=dev

      - name: TypeScript
        run: node_modules/.bin/tsc

      - name: Validate Schema
        uses: docker://contember/cli:1.0.0-rc.15
        with:
          args: project:validate .

      - name: Build Admin
        env:
          NODE_ENV: production
          VITE_USER_NODE_ENV: production
          VITE_CONTEMBER_ADMIN_API_BASE_URL: '/_api'
          VITE_CONTEMBER_ADMIN_SESSION_TOKEN: '__SESSION_TOKEN__'
          VITE_CONTEMBER_ADMIN_SENTRY_DSN: ${{ secrets.ADMIN_SENTRY_DSN }}
        run: node_modules/.bin/vite build "admin" --base "/ukrajina/"

      - name: Deploy Beta
        if: ${{ env.STAGE == 'beta' }}
        uses: docker://contember/cli:1.0.0-rc.15
        env:
          CONTEMBER_API_URL: https://api.ukrajina-beta.contember.cz
          CONTEMBER_API_TOKEN: ${{ secrets.CONTEMBER_BETA_API_TOKEN }}
          CONTEMBER_PROJECT_NAME: ukrajina
        with:
          args: deploy ukrajina --admin https://ukrajina-beta.contember.cz --yes

      - name: Deploy Prod
        if: ${{ env.STAGE == 'prod' }}
        uses: docker://contember/cli:1.0.0-rc.15
        env:
          CONTEMBER_API_URL: https://api.ukrajina.contember.cz
          CONTEMBER_API_TOKEN: ${{ secrets.CONTEMBER_PROD_API_TOKEN }}
          CONTEMBER_PROJECT_NAME: ukrajina
        with:
          args: deploy ukrajina --admin https://ukrajina.contember.cz --yes
